// # SQLx Extension Proc Macro
//
// This proc macro is invoked by the `resource!` macro when a resource declares
// `cinderblock_sqlx` in its `extensions { ... }` block. It receives the full resource
// DSL tokens plus the extension-specific config, and generates an
// `impl SqlResource for <Resource>` block.
//
// # Config syntax
//
// ```text
// cinderblock_sqlx { table = "tickets"; }
// ```
//
// The only required config key is `table`, which specifies the SQLite table
// name for the resource.
//
// # Generated columns
//
// Attributes marked `generated true` are omitted from INSERT and UPDATE
// statements. Their values come from the database (e.g. autoincrement
// primary keys, server-side DEFAULT expressions). The column is still
// included in `COLUMN_NAMES` and `from_row` so that SELECT and RETURNING
// results decode correctly.
//
// # Generated code
//
// For a resource `Ticket` with attributes `ticket_id` (generated),
// `subject`, `status` (where `ticket_id` is the primary key), the macro
// generates:
//
// ```rust,ignore
// impl cinderblock_sqlx::SqlResource for Ticket {
//     const TABLE_NAME: &'static str = "tickets";
//     const COLUMN_NAMES: &'static [&'static str] = &["ticket_id", "subject", "status"];
//     const INSERT_COLUMN_NAMES: &'static [&'static str] = &["subject", "status"];
//     const PRIMARY_KEY_COLUMN: &'static str = "ticket_id";
//
//     fn bind_insert(&self, builder: &mut cinderblock_sqlx::sqlx::QueryBuilder<'_, cinderblock_sqlx::sqlx::Sqlite>) {
//         let mut sep = builder.separated(", ");
//         // ticket_id omitted — generated by database
//         sep.push_bind(self.subject.clone());
//         sep.push_bind(self.status.clone());
//     }
//
//     fn bind_update(&self, builder: &mut cinderblock_sqlx::sqlx::QueryBuilder<'_, cinderblock_sqlx::sqlx::Sqlite>) {
//         let mut sep = builder.separated(", ");
//         // ticket_id omitted — primary key and generated
//         sep.push("subject = ").push_bind_unseparated(self.subject.clone());
//         sep.push("status = ").push_bind_unseparated(self.status.clone());
//     }
//
//     fn bind_primary_key(
//         pk: &<Self as cinderblock_core::Resource>::PrimaryKey,
//         builder: &mut cinderblock_sqlx::sqlx::QueryBuilder<'_, cinderblock_sqlx::sqlx::Sqlite>,
//     ) {
//         builder.push_bind(pk.clone());
//     }
//
//     fn from_row(row: &cinderblock_sqlx::sqlx::sqlite::SqliteRow) -> cinderblock_core::Result<Self> {
//         use cinderblock_sqlx::sqlx::Row;
//         Ok(Self {
//             ticket_id: row.try_get("ticket_id")
//                 .map_err(|e| format!("decode column `ticket_id`: {e}"))?,
//             subject: row.try_get("subject")
//                 .map_err(|e| format!("decode column `subject`: {e}"))?,
//             status: row.try_get("status")
//                 .map_err(|e| format!("decode column `status`: {e}"))?,
//         })
//     }
// }
// ```

use cinderblock_extension_api::{
    ExtensionMacroInput, OrderDirection, ReadFilterValue, RelationDecl, RelationKind,
};
use syn::{Ident, LitStr, Type, parse::Parse};

/// Checks whether a `syn::Type` is `Option<T>`.
fn is_option_type(ty: &Type) -> bool {
    if let Type::Path(type_path) = ty {
        type_path
            .path
            .segments
            .last()
            .is_some_and(|seg| seg.ident == "Option")
    } else {
        false
    }
}

// ---------------------------------------------------------------------------
// # Config Parsing
// ---------------------------------------------------------------------------

/// Extension-specific configuration parsed from inside `config = { ... }`.
///
/// Currently only supports a single required key:
/// - `table = "table_name";` — the SQL table backing this resource
struct SqlxConfig {
    table: String,
}

impl Parse for SqlxConfig {
    fn parse(input: syn::parse::ParseStream) -> syn::Result<Self> {
        let mut table: Option<String> = None;

        while !input.is_empty() {
            let key: Ident = input.fork().parse()?;

            match key.to_string().as_str() {
                "table" => {
                    let (_, value) = cinderblock_extension_api::parse_attribute::<LitStr>(input)?;
                    table = Some(value.value());
                }
                got => {
                    return Err(syn::Error::new(
                        key.span(),
                        format!("unexpected cinderblock_sqlx config key, got `{got}`"),
                    ));
                }
            }
        }

        let table = table.ok_or_else(|| {
            syn::Error::new(
                proc_macro2::Span::call_site(),
                "cinderblock_sqlx config requires `table = \"...\";`",
            )
        })?;

        Ok(SqlxConfig { table })
    }
}

// ---------------------------------------------------------------------------
// # Code Generation
// ---------------------------------------------------------------------------

#[proc_macro]
pub fn __resource_extension(item: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let input = syn::parse_macro_input!(item as ExtensionMacroInput<SqlxConfig>);

    let resource = &input.resource;
    let config = &input.config;

    // Derive the resource struct name from the last segment of the dotted name.
    let ident = resource
        .name
        .last()
        .expect("resource name must have at least one segment");

    let table_name = &config.table;

    // # Column metadata
    //
    // Build the list of all column names (matching attribute names) and
    // identify the primary key column. `INSERT_COLUMN_NAMES` excludes
    // columns marked `generated true` — those values come from the
    // database (e.g. autoincrement, server-side DEFAULT).
    let column_names: Vec<String> = resource
        .attributes
        .iter()
        .map(|attr| attr.name.to_string())
        .collect();

    let insert_column_names: Vec<String> = resource
        .attributes
        .iter()
        .filter(|attr| !attr.generated.value())
        .map(|attr| attr.name.to_string())
        .collect();

    let primary_key_attr = resource
        .attributes
        .iter()
        .find(|attr| attr.primary_key.value())
        .expect("resource must have a primary key attribute");

    let pk_column = primary_key_attr.name.to_string();

    // # bind_insert
    //
    // Generates a `sep.push_bind(self.<field>.clone())` call for every
    // non-generated attribute, in declaration order. The separated helper
    // auto-inserts `, ` between bind placeholders. Generated columns are
    // omitted — their values come from the database.
    let bind_insert_calls: Vec<_> = resource
        .attributes
        .iter()
        .filter(|attr| !attr.generated.value())
        .map(|attr| {
            let field = &attr.name;
            quote::quote! {
                sep.push_bind(self.#field.clone());
            }
        })
        .collect();

    // # bind_update
    //
    // Generates `col = ?` pairs for every attribute that is neither the
    // primary key nor generated. We use `Separated::push("col = ")`
    // followed by `.push_bind_unseparated()` so each pair is
    // comma-separated but the `= ?` stays glued to its column name.
    let non_pk_non_generated_attributes: Vec<_> = resource
        .attributes
        .iter()
        .filter(|attr| !attr.primary_key.value() && !attr.generated.value())
        .collect();

    let bind_update_calls: Vec<_> = non_pk_non_generated_attributes
        .iter()
        .map(|attr| {
            let field = &attr.name;
            let col_eq = format!("{} = ", attr.name);
            quote::quote! {
                sep.push(#col_eq).push_bind_unseparated(self.#field.clone());
            }
        })
        .collect();

    // # from_row
    //
    // Generates a `row.try_get("column")` call for each attribute. We
    // map sqlx errors to a boxed error type with a descriptive message
    // including the column name. Callers wrap this into their
    // action-specific error variant.
    let from_row_fields: Vec<_> = resource
        .attributes
        .iter()
        .map(|attr| {
            let field = &attr.name;
            let col = attr.name.to_string();
            quote::quote! {
                #field: row.try_get(#col)
                    .map_err(|e| -> Box<dyn ::std::error::Error + Send + Sync> {
                        format!("decode column `{}`: {e}", #col).into()
                    })?,
            }
        })
        .collect();

    // # Column name literals for the consts
    let column_name_literals: Vec<_> = column_names.iter().map(|c| quote::quote! { #c }).collect();
    let insert_column_name_literals: Vec<_> = insert_column_names
        .iter()
        .map(|c| quote::quote! { #c })
        .collect();

    let relations = &input.resource.relations;

    let read_actions = input
        .resource
        .actions
        .iter()
        .filter_map(|action| match &action.kind {
            cinderblock_extension_api::ResourceActionInputKind::Read(action_read) => {
                Some((action, action_read))
            }
            _ => None,
        })
        .map(|(action, action_read)| {
            // TODO: This should come from the parsing crate
            let action_name = convert_case::ccase!(pascal, action.name.to_string());
            let action_name = Ident::new(&action_name, action.name.span());

            let has_loads = !action_read.load.is_empty();

            // Get-actions without load delegate to `execute_sql_read_one` —
            // no filters, no ordering, just a primary key lookup.
            if action_read.get && !has_loads {
                return quote::quote! {
                    impl cinderblock_sqlx::SqlPerformReadOne for #action_name {
                        async fn execute(
                            pool: &cinderblock_sqlx::sqlx::SqlitePool,
                            args: &Self::Arguments,
                        ) -> Result<Self::Response, cinderblock_core::ReadError> {
                            cinderblock_sqlx::execute_sql_read_one::<#ident>(pool, args).await
                        }
                    }
                };
            }

            // Get-actions with load: fetch base row by PK, then run
            // batched relation queries, assemble wrapper.
            if action_read.get && has_loads {
                let loaded_relations: Vec<&RelationDecl> = action_read
                    .load
                    .iter()
                    .map(|name| {
                        relations
                            .iter()
                            .find(|r| r.name == *name)
                            .expect("load reference validated during parsing")
                    })
                    .collect();

                let wrapper_name =
                    Ident::new(&format!("{action_name}Response"), action.name.span());

                let relation_loads = loaded_relations.iter().map(|rel| {
                    let rel_ty = &rel.ty;
                    let source_attr = &rel.source_attribute;
                    let map_name = Ident::new(
                        &format!("{}_map", rel.name),
                        rel.name.span(),
                    );

                    match rel.kind {
                        RelationKind::BelongsTo => {
                            let fk_attr = resource
                                .attributes
                                .iter()
                                .find(|a| a.name == *source_attr)
                                .expect("source_attribute must reference a declared attribute");
                            let fk_type = &fk_attr.ty;

                            quote::quote! {
                                let #map_name: ::std::collections::HashMap<String, #rel_ty> = {
                                    let fk_values: Vec<#fk_type> = vec![base.#source_attr.clone()];

                                    let related_table = <#rel_ty as cinderblock_sqlx::SqlResource>::TABLE_NAME;
                                    let related_pk_col = <#rel_ty as cinderblock_sqlx::SqlResource>::PRIMARY_KEY_COLUMN;

                                    let mut builder = cinderblock_sqlx::sqlx::QueryBuilder::new(
                                        format!("SELECT * FROM {} WHERE {} IN (", related_table, related_pk_col)
                                    );

                                    let mut sep = builder.separated(", ");
                                    for val in &fk_values {
                                        sep.push_bind(val.clone());
                                    }
                                    builder.push(")");

                                    let rows: Vec<cinderblock_sqlx::sqlx::sqlite::SqliteRow> = builder
                                        .build()
                                        .fetch_all(pool)
                                        .await
                                        .map_err(|e| {
                                            cinderblock_core::ReadError::DataLayer(
                                                format!(
                                                    "load belongs_to relation from `{}`: {e}",
                                                    related_table,
                                                ).into(),
                                            )
                                        })?;

                                    let mut map = ::std::collections::HashMap::with_capacity(rows.len());
                                    for row in &rows {
                                        let related = <#rel_ty as cinderblock_sqlx::SqlResource>::from_row(row)
                                            .map_err(cinderblock_core::ReadError::DataLayer)?;
                                        use cinderblock_core::Resource;
                                        map.insert(related.primary_key().to_string(), related);
                                    }
                                    map
                                };
                            }
                        }
                        RelationKind::HasMany => {
                            let source_attr_str = source_attr.to_string();
                            let pk_type = &primary_key_attr.ty;

                            quote::quote! {
                                let #map_name: ::std::collections::HashMap<String, Vec<#rel_ty>> = {
                                    let pk_values: Vec<#pk_type> = vec![{
                                        use cinderblock_core::Resource;
                                        base.primary_key().clone()
                                    }];

                                    let related_table = <#rel_ty as cinderblock_sqlx::SqlResource>::TABLE_NAME;

                                    let mut builder = cinderblock_sqlx::sqlx::QueryBuilder::new(
                                        format!("SELECT * FROM {} WHERE {} IN (", related_table, #source_attr_str)
                                    );

                                    let mut sep = builder.separated(", ");
                                    for val in &pk_values {
                                        sep.push_bind(val.clone());
                                    }
                                    builder.push(")");

                                    let rows: Vec<cinderblock_sqlx::sqlx::sqlite::SqliteRow> = builder
                                        .build()
                                        .fetch_all(pool)
                                        .await
                                        .map_err(|e| {
                                            cinderblock_core::ReadError::DataLayer(
                                                format!(
                                                    "load has_many relation from `{}`: {e}",
                                                    related_table,
                                                ).into(),
                                            )
                                        })?;

                                    let mut map: ::std::collections::HashMap<String, Vec<#rel_ty>> =
                                        ::std::collections::HashMap::new();
                                    for row in &rows {
                                        let related = <#rel_ty as cinderblock_sqlx::SqlResource>::from_row(row)
                                            .map_err(cinderblock_core::ReadError::DataLayer)?;
                                        let key = related.#source_attr.to_string();
                                        map.entry(key).or_default().push(related);
                                    }
                                    map
                                };
                            }
                        }
                    }
                });

                let relation_field_inits = loaded_relations.iter().map(|rel| {
                    let rel_name = &rel.name;
                    let source_attr = &rel.source_attribute;
                    let map_name = Ident::new(
                        &format!("{}_map", rel.name),
                        rel.name.span(),
                    );

                    match rel.kind {
                        RelationKind::BelongsTo => {
                            let rel_ty = &rel.ty;
                            let rel_name_str = rel.name.to_string();
                            quote::quote! {
                                #rel_name: #map_name
                                    .get(&base.#source_attr.to_string())
                                    .cloned()
                                    .ok_or_else(|| {
                                        cinderblock_core::ReadError::DataLayer(
                                            format!(
                                                "belongs_to relation `{}` of type `{}`: no record found for FK value `{}`",
                                                #rel_name_str,
                                                ::std::any::type_name::<#rel_ty>(),
                                                base.#source_attr,
                                            ).into(),
                                        )
                                    })?
                            }
                        }
                        RelationKind::HasMany => {
                            quote::quote! {
                                #rel_name: {
                                    use cinderblock_core::Resource;
                                    #map_name
                                        .get(&base.primary_key().to_string())
                                        .cloned()
                                        .unwrap_or_default()
                                }
                            }
                        }
                    }
                });

                return quote::quote! {
                    impl cinderblock_sqlx::SqlPerformReadOne for #action_name {
                        async fn execute(
                            pool: &cinderblock_sqlx::sqlx::SqlitePool,
                            args: &Self::Arguments,
                        ) -> Result<Self::Response, cinderblock_core::ReadError> {
                            use cinderblock_sqlx::sqlx::Row;

                            let base = cinderblock_sqlx::execute_sql_read_one::<#ident>(pool, args).await?;

                            #(#relation_loads)*

                            Ok(#wrapper_name {
                                #(#relation_field_inits,)*
                                base,
                            })
                        }
                    }
                };
            }

            let has_loads = !action_read.load.is_empty();

            // # SQL filter generation
            //
            // We split filters into two categories:
            //
            // 1. **Static filters** — always applied (literal values and
            //    required `arg()` references). These are unconditionally
            //    pushed into the WHERE clause.
            //
            // 2. **Conditional filters** — `arg()` references to `Option<T>`
            //    arguments. These are only added to the WHERE clause when
            //    the argument value is `Some`.
            //
            // Because optional arguments make the total number of WHERE
            // clauses unknown at compile time, `bind_filters` handles
            // emitting the WHERE keyword and AND separators dynamically
            // using a `filter_count` counter.

            let filter_stmts: Vec<_> = action_read.filters.iter().map(|filter| {
                let field_str = filter.field.to_string();
                let op = match filter.op {
                    cinderblock_extension_api::ReadFilterOperation::Eq => "=",
                };

                match &filter.value {
                    ReadFilterValue::Literal(expr) => {
                        quote::quote! {
                            if filter_count > 0 { builder.push(" AND "); } else { builder.push("WHERE "); }
                            builder.push(format!("{} {} ", #field_str, #op)).push_bind(#expr);
                            filter_count += 1;
                        }
                    }
                    ReadFilterValue::Arg(arg_name) => {
                        let arg_decl = action_read
                            .arguments
                            .iter()
                            .find(|a| a.name == *arg_name)
                            .expect("arg reference validated during parsing");

                        if is_option_type(&arg_decl.ty) {
                            // Optional: only push the clause when Some
                            quote::quote! {
                                if let Some(ref val) = args.#arg_name {
                                    if filter_count > 0 { builder.push(" AND "); } else { builder.push("WHERE "); }
                                    builder.push(format!("{} {} ", #field_str, #op)).push_bind(val.clone());
                                    filter_count += 1;
                                }
                            }
                        } else {
                            // Required: always push
                            quote::quote! {
                                if filter_count > 0 { builder.push(" AND "); } else { builder.push("WHERE "); }
                                builder.push(format!("{} {} ", #field_str, #op)).push_bind(args.#arg_name.clone());
                                filter_count += 1;
                            }
                        }
                    }
                }
            }).collect();

            // Build a static ORDER BY clause string at compile time.
            // No bind parameters needed — column names and directions are literals.
            let order_by_push = if action_read.orders.is_empty() {
                quote::quote! {}
            } else {
                let clause = action_read.orders.iter()
                    .map(|o| {
                        let col = o.field.to_string();
                        let dir = match o.direction {
                            OrderDirection::Asc  => "ASC",
                            OrderDirection::Desc => "DESC",
                        };
                        format!("{col} {dir}")
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                let order_sql = format!(" ORDER BY {clause}");
                quote::quote! { builder.push(#order_sql); }
            };

            // Choose `SqlPagedReadAction` or `SqlReadAction` based on
            // whether the action is paged. The filter body is identical
            // for both; only the trait name differs.
            let is_paged = action_read.paged.is_some();

            if has_loads {
                // # Relation-loading SqlPerformRead codegen
                //
                // For read actions with `load [...]`, we skip the normal
                // SqlReadAction/SqlPagedReadAction trait impls and instead
                // generate a direct `SqlPerformRead` that:
                //   1. Runs the base SELECT query with filters
                //   2. For each loaded relation, runs a batched SELECT
                //      using `WHERE column IN (?, ?, ...)` to load related
                //      rows in a single query (N+1 safe)
                //   3. Assembles the response wrapper structs
                //
                // TODO: support paged + load combination
                let loaded_relations: Vec<&RelationDecl> = action_read
                    .load
                    .iter()
                    .map(|name| {
                        relations
                            .iter()
                            .find(|r| r.name == *name)
                            .expect("load reference validated during parsing")
                    })
                    .collect();

                let wrapper_name =
                    Ident::new(&format!("{action_name}Response"), action.name.span());

                // # Relation loading queries
                //
                // For each relation, generate code that:
                //   - Collects the lookup keys from base rows (as their actual
                //     Rust type, NOT as String — this matters because sqlx encodes
                //     types like `Uuid` as BLOBs, not TEXT)
                //   - Builds a `SELECT * FROM related_table WHERE col IN (?, ...)`
                //   - Decodes rows and builds a lookup HashMap (keyed by String
                //     for convenience, since HashMap lookup only needs equality)
                let relation_loads = loaded_relations.iter().map(|rel| {
                    let rel_ty = &rel.ty;
                    let source_attr = &rel.source_attribute;
                    let map_name = Ident::new(
                        &format!("{}_map", rel.name),
                        rel.name.span(),
                    );

                    match rel.kind {
                        RelationKind::BelongsTo => {
                            // For belongs_to: the FK is on the base resource,
                            // pointing to the related resource's PK. We collect
                            // FK values from base rows, then query the related
                            // table with `WHERE pk_column IN (...)`.
                            //
                            // We bind the FK values using their actual Rust type
                            // (looked up from the resource's attribute list) so
                            // that sqlx encodes them correctly (e.g. Uuid → BLOB).
                            let fk_attr = resource
                                .attributes
                                .iter()
                                .find(|a| a.name == *source_attr)
                                .expect("source_attribute must reference a declared attribute");
                            let fk_type = &fk_attr.ty;

                            quote::quote! {
                                let #map_name: ::std::collections::HashMap<String, #rel_ty> = {
                                    // Collect unique FK values as their native type
                                    let fk_values: Vec<#fk_type> = base_rows
                                        .iter()
                                        .map(|r| r.#source_attr.clone())
                                        .collect::<::std::collections::HashSet<_>>()
                                        .into_iter()
                                        .collect();

                                    if fk_values.is_empty() {
                                        ::std::collections::HashMap::new()
                                    } else {
                                        let related_table = <#rel_ty as cinderblock_sqlx::SqlResource>::TABLE_NAME;
                                        let related_pk_col = <#rel_ty as cinderblock_sqlx::SqlResource>::PRIMARY_KEY_COLUMN;

                                        let mut builder = cinderblock_sqlx::sqlx::QueryBuilder::new(
                                            format!("SELECT * FROM {} WHERE {} IN (", related_table, related_pk_col)
                                        );

                                        let mut sep = builder.separated(", ");
                                        for val in &fk_values {
                                            sep.push_bind(val.clone());
                                        }
                                        builder.push(")");

                                        let rows: Vec<cinderblock_sqlx::sqlx::sqlite::SqliteRow> = builder
                                            .build()
                                            .fetch_all(pool)
                                            .await
                                            .map_err(|e| {
                                                cinderblock_core::ListError::DataLayer(
                                                    format!(
                                                        "load belongs_to relation from `{}`: {e}",
                                                        related_table,
                                                    ).into(),
                                                )
                                            })?;

                                        let mut map = ::std::collections::HashMap::with_capacity(rows.len());
                                        for row in &rows {
                                            let related = <#rel_ty as cinderblock_sqlx::SqlResource>::from_row(row)
                                                .map_err(cinderblock_core::ListError::DataLayer)?;
                                            use cinderblock_core::Resource;
                                            map.insert(related.primary_key().to_string(), related);
                                        }
                                        map
                                    }
                                };
                            }
                        }
                        RelationKind::HasMany => {
                            // For has_many: the FK is on the related resource,
                            // pointing back to the base resource's PK. We collect
                            // PK values from base rows, then query the related
                            // table with `WHERE fk_column IN (...)`.
                            //
                            // We bind the PK values using their actual Rust type
                            // so that sqlx encodes them correctly.
                            let source_attr_str = source_attr.to_string();
                            let pk_type = &primary_key_attr.ty;

                            quote::quote! {
                                let #map_name: ::std::collections::HashMap<String, Vec<#rel_ty>> = {
                                    // Collect unique PK values as their native type
                                    let pk_values: Vec<#pk_type> = base_rows
                                        .iter()
                                        .map(|r| {
                                            use cinderblock_core::Resource;
                                            r.primary_key().clone()
                                        })
                                        .collect::<::std::collections::HashSet<_>>()
                                        .into_iter()
                                        .collect();

                                    if pk_values.is_empty() {
                                        ::std::collections::HashMap::new()
                                    } else {
                                        let related_table = <#rel_ty as cinderblock_sqlx::SqlResource>::TABLE_NAME;

                                        let mut builder = cinderblock_sqlx::sqlx::QueryBuilder::new(
                                            format!("SELECT * FROM {} WHERE {} IN (", related_table, #source_attr_str)
                                        );

                                        let mut sep = builder.separated(", ");
                                        for val in &pk_values {
                                            sep.push_bind(val.clone());
                                        }
                                        builder.push(")");

                                        let rows: Vec<cinderblock_sqlx::sqlx::sqlite::SqliteRow> = builder
                                            .build()
                                            .fetch_all(pool)
                                            .await
                                            .map_err(|e| {
                                                cinderblock_core::ListError::DataLayer(
                                                    format!(
                                                        "load has_many relation from `{}`: {e}",
                                                        related_table,
                                                    ).into(),
                                                )
                                            })?;

                                        let mut map: ::std::collections::HashMap<String, Vec<#rel_ty>> =
                                            ::std::collections::HashMap::new();
                                        for row in &rows {
                                            let related = <#rel_ty as cinderblock_sqlx::SqlResource>::from_row(row)
                                                .map_err(cinderblock_core::ListError::DataLayer)?;
                                            let key = related.#source_attr.to_string();
                                            map.entry(key).or_default().push(related);
                                        }
                                        map
                                    }
                                };
                            }
                        }
                    }
                });

                // # Wrapper assembly for each base row
                let relation_field_inits = loaded_relations.iter().map(|rel| {
                    let rel_name = &rel.name;
                    let source_attr = &rel.source_attribute;
                    let map_name = Ident::new(
                        &format!("{}_map", rel.name),
                        rel.name.span(),
                    );

                    match rel.kind {
                        RelationKind::BelongsTo => {
                            let rel_ty = &rel.ty;
                            let rel_name_str = rel.name.to_string();
                            quote::quote! {
                                #rel_name: #map_name
                                    .get(&row.#source_attr.to_string())
                                    .cloned()
                                    .ok_or_else(|| {
                                        cinderblock_core::ListError::DataLayer(
                                            format!(
                                                "belongs_to relation `{}` of type `{}`: no record found for FK value `{}`",
                                                #rel_name_str,
                                                ::std::any::type_name::<#rel_ty>(),
                                                row.#source_attr,
                                            ).into(),
                                        )
                                    })?
                            }
                        }
                        RelationKind::HasMany => {
                            quote::quote! {
                                #rel_name: {
                                    use cinderblock_core::Resource;
                                    #map_name
                                        .get(&row.primary_key().to_string())
                                        .cloned()
                                        .unwrap_or_default()
                                }
                            }
                        }
                    }
                });

                quote::quote! {
                    impl cinderblock_sqlx::SqlPerformRead for #action_name {
                        async fn execute(
                            pool: &cinderblock_sqlx::sqlx::SqlitePool,
                            args: &Self::Arguments,
                        ) -> Result<Self::Response, cinderblock_core::ListError> {
                            use cinderblock_sqlx::sqlx::Row;

                            // Step 1: Run the base query with filters
                            let base_rows: Vec<#ident> = {
                                let mut builder = cinderblock_sqlx::sqlx::QueryBuilder::new(format!(
                                    "SELECT * FROM {} ",
                                    <#ident as cinderblock_sqlx::SqlResource>::TABLE_NAME,
                                ));

                                let mut filter_count: u32 = 0;
                                #(#filter_stmts)*
                                let _ = filter_count; // suppress unused warning when no filters

                                #order_by_push

                                let rows: Vec<cinderblock_sqlx::sqlx::sqlite::SqliteRow> = builder
                                    .build()
                                    .fetch_all(pool)
                                    .await
                                    .map_err(|e| {
                                        cinderblock_core::ListError::DataLayer(
                                            format!(
                                                "read from `{}`: {e}",
                                                <#ident as cinderblock_sqlx::SqlResource>::TABLE_NAME,
                                            ).into(),
                                        )
                                    })?;

                                let mut result = Vec::with_capacity(rows.len());
                                for row in &rows {
                                    result.push(
                                        <#ident as cinderblock_sqlx::SqlResource>::from_row(row)
                                            .map_err(cinderblock_core::ListError::DataLayer)?
                                    );
                                }
                                result
                            };

                            // Step 2: Load related resources via batched queries
                            #(#relation_loads)*

                            // Step 3: Assemble response wrappers
                            let results: Result<Vec<#wrapper_name>, cinderblock_core::ListError> = base_rows
                                .into_iter()
                                .map(|row| -> Result<#wrapper_name, cinderblock_core::ListError> {
                                    Ok(#wrapper_name {
                                        #(#relation_field_inits,)*
                                        base: row,
                                    })
                                })
                                .collect();

                            results
                        }
                    }
                }
            } else {
                // # Standard read action codegen (no relation loading)

                let trait_path = if is_paged {
                    quote::quote! { cinderblock_sqlx::SqlPagedReadAction }
                } else {
                    quote::quote! { cinderblock_sqlx::SqlReadAction }
                };

                // Generate `SqlPerformRead` that delegates to the appropriate
                // standalone execute function.
                let perform_read_body = if is_paged {
                    quote::quote! {
                        cinderblock_sqlx::execute_sql_paged_read::<Self>(pool, args).await
                    }
                } else {
                    quote::quote! {
                        cinderblock_sqlx::execute_sql_read::<Self>(pool, args).await
                    }
                };

                quote::quote! {
                    impl #trait_path for #action_name {
                        fn bind_filters(
                            builder: &mut cinderblock_sqlx::sqlx::QueryBuilder<'_, cinderblock_sqlx::sqlx::Sqlite>,
                            args: &Self::Arguments,
                        ) -> bool {
                            let mut filter_count: u32 = 0;
                            #(#filter_stmts)*
                            filter_count > 0
                        }

                        fn bind_order(
                            builder: &mut cinderblock_sqlx::sqlx::QueryBuilder<'_, cinderblock_sqlx::sqlx::Sqlite>,
                        ) {
                            #order_by_push
                        }
                    }

                    impl cinderblock_sqlx::SqlPerformRead for #action_name {
                        async fn execute(
                            pool: &cinderblock_sqlx::sqlx::SqlitePool,
                            args: &Self::Arguments,
                        ) -> Result<Self::Response, cinderblock_core::ListError> {
                            #perform_read_body
                        }
                    }
                }
            }
        });

    quote::quote! {
        impl cinderblock_sqlx::SqlResource for #ident {
            const TABLE_NAME: &'static str = #table_name;
            const COLUMN_NAMES: &'static [&'static str] = &[#(#column_name_literals),*];
            const INSERT_COLUMN_NAMES: &'static [&'static str] = &[#(#insert_column_name_literals),*];
            const PRIMARY_KEY_COLUMN: &'static str = #pk_column;

            fn bind_insert(
                &self,
                builder: &mut cinderblock_sqlx::sqlx::QueryBuilder<'_, cinderblock_sqlx::sqlx::Sqlite>,
            ) {
                let mut sep = builder.separated(", ");
                #(#bind_insert_calls)*
            }

            fn bind_update(
                &self,
                builder: &mut cinderblock_sqlx::sqlx::QueryBuilder<'_, cinderblock_sqlx::sqlx::Sqlite>,
            ) {
                let mut sep = builder.separated(", ");
                #(#bind_update_calls)*
            }

            fn bind_primary_key(
                pk: &<Self as cinderblock_core::Resource>::PrimaryKey,
                builder: &mut cinderblock_sqlx::sqlx::QueryBuilder<'_, cinderblock_sqlx::sqlx::Sqlite>,
            ) {
                builder.push_bind(pk.clone());
            }

            fn from_row(
                row: &cinderblock_sqlx::sqlx::sqlite::SqliteRow,
            ) -> Result<Self, Box<dyn ::std::error::Error + Send + Sync>> {
                use cinderblock_sqlx::sqlx::Row;
                Ok(Self {
                    #(#from_row_fields)*
                })
            }
        }

        #(#read_actions)*
    }
    .into()
}

// ---------------------------------------------------------------------------
// # Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use assert2::{assert, check};

    use super::*;

    fn parse_config(tokens: proc_macro2::TokenStream) -> SqlxConfig {
        let result = syn::parse2::<SqlxConfig>(tokens);
        assert!(let Ok(config) = result);
        config
    }

    #[test]
    fn parse_table_config() {
        let config = parse_config(quote::quote! {
            table = "tickets";
        });

        check!(config.table == "tickets");
    }

    #[test]
    fn missing_table_produces_error() {
        let result = syn::parse2::<SqlxConfig>(quote::quote! {});

        assert!(let Err(err) = result);
        let msg = err.to_string();
        check!(msg.contains("requires `table"));
    }

    #[test]
    fn unknown_config_key_produces_error() {
        let result = syn::parse2::<SqlxConfig>(quote::quote! {
            table = "tickets";
            bogus = "value";
        });

        assert!(let Err(err) = result);
        let msg = err.to_string();
        check!(msg.contains("unexpected cinderblock_sqlx config key"));
        check!(msg.contains("bogus"));
    }

    #[test]
    fn table_with_schema_prefix() {
        let config = parse_config(quote::quote! {
            table = "helpdesk_tickets";
        });

        check!(config.table == "helpdesk_tickets");
    }

    // Verify the full extension input parses correctly — this uses the
    // same `ExtensionMacroInput<SqlxConfig>` that the proc macro does.
    #[test]
    fn parse_full_extension_input() {
        let tokens = quote::quote! {
            {
                name = Helpdesk.Support.Ticket;

                attributes {
                    ticket_id Uuid {
                        primary_key true;
                        writable false;
                        default || uuid::Uuid::new_v4();
                    }
                    subject String;
                    status TicketStatus;
                }

                actions {
                    create open;
                }
            }

            config = {
                table = "tickets";
            }
        };

        let result = syn::parse2::<ExtensionMacroInput<SqlxConfig>>(tokens);
        assert!(let Ok(input) = result);
        check!(input.config.table == "tickets");
        check!(input.resource.attributes.len() == 3);

        // Verify primary key detection.
        let pk = input
            .resource
            .attributes
            .iter()
            .find(|a| a.primary_key.value());
        assert!(let Some(pk_attr) = pk);
        check!(pk_attr.name == "ticket_id");
    }
}
