// # SQLx Extension Proc Macro
//
// This proc macro is invoked by the `resource!` macro when a resource declares
// `cinderblock_sqlx` in its `extensions { ... }` block. It receives the full resource
// DSL tokens plus the extension-specific config, and generates an
// `impl SqlResource for <Resource>` block.
//
// # Config syntax
//
// ```text
// cinderblock_sqlx { table = "tickets"; }
// ```
//
// The only required config key is `table`, which specifies the SQLite table
// name for the resource.
//
// # Generated columns
//
// Attributes marked `generated true` are omitted from INSERT and UPDATE
// statements. Their values come from the database (e.g. autoincrement
// primary keys, server-side DEFAULT expressions). The column is still
// included in `COLUMN_NAMES` and `from_row` so that SELECT and RETURNING
// results decode correctly.
//
// # Generated code
//
// For a resource `Ticket` with attributes `ticket_id` (generated),
// `subject`, `status` (where `ticket_id` is the primary key), the macro
// generates:
//
// ```rust,ignore
// impl cinderblock_sqlx::SqlResource for Ticket {
//     const TABLE_NAME: &'static str = "tickets";
//     const COLUMN_NAMES: &'static [&'static str] = &["ticket_id", "subject", "status"];
//     const INSERT_COLUMN_NAMES: &'static [&'static str] = &["subject", "status"];
//     const PRIMARY_KEY_COLUMN: &'static str = "ticket_id";
//
//     fn bind_insert(&self, builder: &mut cinderblock_sqlx::sqlx::QueryBuilder<'_, cinderblock_sqlx::sqlx::Sqlite>) {
//         let mut sep = builder.separated(", ");
//         // ticket_id omitted — generated by database
//         sep.push_bind(self.subject.clone());
//         sep.push_bind(self.status.clone());
//     }
//
//     fn bind_update(&self, builder: &mut cinderblock_sqlx::sqlx::QueryBuilder<'_, cinderblock_sqlx::sqlx::Sqlite>) {
//         let mut sep = builder.separated(", ");
//         // ticket_id omitted — primary key and generated
//         sep.push("subject = ").push_bind_unseparated(self.subject.clone());
//         sep.push("status = ").push_bind_unseparated(self.status.clone());
//     }
//
//     fn bind_primary_key(
//         pk: &<Self as cinderblock_core::Resource>::PrimaryKey,
//         builder: &mut cinderblock_sqlx::sqlx::QueryBuilder<'_, cinderblock_sqlx::sqlx::Sqlite>,
//     ) {
//         builder.push_bind(pk.clone());
//     }
//
//     fn from_row(row: &cinderblock_sqlx::sqlx::sqlite::SqliteRow) -> cinderblock_core::Result<Self> {
//         use cinderblock_sqlx::sqlx::Row;
//         Ok(Self {
//             ticket_id: row.try_get("ticket_id")
//                 .map_err(|e| format!("decode column `ticket_id`: {e}"))?,
//             subject: row.try_get("subject")
//                 .map_err(|e| format!("decode column `subject`: {e}"))?,
//             status: row.try_get("status")
//                 .map_err(|e| format!("decode column `status`: {e}"))?,
//         })
//     }
// }
// ```

use cinderblock_extension_api::{ExtensionMacroInput, ReadFilterValue};
use syn::{parse::Parse, Ident, LitStr, Type};

/// Checks whether a `syn::Type` is `Option<T>`.
fn is_option_type(ty: &Type) -> bool {
    if let Type::Path(type_path) = ty {
        type_path
            .path
            .segments
            .last()
            .is_some_and(|seg| seg.ident == "Option")
    } else {
        false
    }
}

// ---------------------------------------------------------------------------
// # Config Parsing
// ---------------------------------------------------------------------------

/// Extension-specific configuration parsed from inside `config = { ... }`.
///
/// Currently only supports a single required key:
/// - `table = "table_name";` — the SQL table backing this resource
struct SqlxConfig {
    table: String,
}

impl Parse for SqlxConfig {
    fn parse(input: syn::parse::ParseStream) -> syn::Result<Self> {
        let mut table: Option<String> = None;

        while !input.is_empty() {
            let key: Ident = input.fork().parse()?;

            match key.to_string().as_str() {
                "table" => {
                    let (_, value) = cinderblock_extension_api::parse_attribute::<LitStr>(input)?;
                    table = Some(value.value());
                }
                got => {
                    return Err(syn::Error::new(
                        key.span(),
                        format!("unexpected cinderblock_sqlx config key, got `{got}`"),
                    ));
                }
            }
        }

        let table = table.ok_or_else(|| {
            syn::Error::new(
                proc_macro2::Span::call_site(),
                "cinderblock_sqlx config requires `table = \"...\";`",
            )
        })?;

        Ok(SqlxConfig { table })
    }
}

// ---------------------------------------------------------------------------
// # Code Generation
// ---------------------------------------------------------------------------

#[proc_macro]
pub fn __resource_extension(item: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let input = syn::parse_macro_input!(item as ExtensionMacroInput<SqlxConfig>);

    let resource = &input.resource;
    let config = &input.config;

    // Derive the resource struct name from the last segment of the dotted name.
    let ident = resource
        .name
        .last()
        .expect("resource name must have at least one segment");

    let table_name = &config.table;

    // # Column metadata
    //
    // Build the list of all column names (matching attribute names) and
    // identify the primary key column. `INSERT_COLUMN_NAMES` excludes
    // columns marked `generated true` — those values come from the
    // database (e.g. autoincrement, server-side DEFAULT).
    let column_names: Vec<String> = resource
        .attributes
        .iter()
        .map(|attr| attr.name.to_string())
        .collect();

    let insert_column_names: Vec<String> = resource
        .attributes
        .iter()
        .filter(|attr| !attr.generated.value())
        .map(|attr| attr.name.to_string())
        .collect();

    let primary_key_attr = resource
        .attributes
        .iter()
        .find(|attr| attr.primary_key.value())
        .expect("resource must have a primary key attribute");

    let pk_column = primary_key_attr.name.to_string();

    // # bind_insert
    //
    // Generates a `sep.push_bind(self.<field>.clone())` call for every
    // non-generated attribute, in declaration order. The separated helper
    // auto-inserts `, ` between bind placeholders. Generated columns are
    // omitted — their values come from the database.
    let bind_insert_calls: Vec<_> = resource
        .attributes
        .iter()
        .filter(|attr| !attr.generated.value())
        .map(|attr| {
            let field = &attr.name;
            quote::quote! {
                sep.push_bind(self.#field.clone());
            }
        })
        .collect();

    // # bind_update
    //
    // Generates `col = ?` pairs for every attribute that is neither the
    // primary key nor generated. We use `Separated::push("col = ")`
    // followed by `.push_bind_unseparated()` so each pair is
    // comma-separated but the `= ?` stays glued to its column name.
    let non_pk_non_generated_attributes: Vec<_> = resource
        .attributes
        .iter()
        .filter(|attr| !attr.primary_key.value() && !attr.generated.value())
        .collect();

    let bind_update_calls: Vec<_> = non_pk_non_generated_attributes
        .iter()
        .map(|attr| {
            let field = &attr.name;
            let col_eq = format!("{} = ", attr.name);
            quote::quote! {
                sep.push(#col_eq).push_bind_unseparated(self.#field.clone());
            }
        })
        .collect();

    // # from_row
    //
    // Generates a `row.try_get("column")` call for each attribute. We
    // map sqlx errors to our `cinderblock_core::Result` error type with a
    // descriptive message including the column name.
    let from_row_fields: Vec<_> = resource
        .attributes
        .iter()
        .map(|attr| {
            let field = &attr.name;
            let col = attr.name.to_string();
            quote::quote! {
                #field: row.try_get(#col)
                    .map_err(|e| format!("decode column `{}`: {e}", #col))?,
            }
        })
        .collect();

    // # Column name literals for the consts
    let column_name_literals: Vec<_> = column_names.iter().map(|c| quote::quote! { #c }).collect();
    let insert_column_name_literals: Vec<_> = insert_column_names
        .iter()
        .map(|c| quote::quote! { #c })
        .collect();

    let read_actions = input
        .resource
        .actions
        .iter()
        .filter_map(|action| match &action.kind {
            cinderblock_extension_api::ResourceActionInputKind::Read(action_read) => {
                Some((action, action_read))
            }
            _ => None,
        })
        .map(|(action, action_read)| {
            // TODO: This should come from the parsing crate
            let action_name = convert_case::ccase!(pascal, action.name.to_string());
            let action_name = Ident::new(&action_name, action.name.span());

            // # SQL filter generation
            //
            // We split filters into two categories:
            //
            // 1. **Static filters** — always applied (literal values and
            //    required `arg()` references). These are unconditionally
            //    pushed into the WHERE clause.
            //
            // 2. **Conditional filters** — `arg()` references to `Option<T>`
            //    arguments. These are only added to the WHERE clause when
            //    the argument value is `Some`.
            //
            // Because optional arguments make the total number of WHERE
            // clauses unknown at compile time, `bind_filters` handles
            // emitting the WHERE keyword and AND separators dynamically
            // using a `filter_count` counter.

            let filter_stmts: Vec<_> = action_read.filters.iter().map(|filter| {
                let field_str = filter.field.to_string();
                let op = match filter.op {
                    cinderblock_extension_api::ReadFilterOperation::Eq => "=",
                };

                match &filter.value {
                    ReadFilterValue::Literal(expr) => {
                        quote::quote! {
                            if filter_count > 0 { builder.push(" AND "); } else { builder.push("WHERE "); }
                            builder.push(format!("{} {} ", #field_str, #op)).push_bind(#expr);
                            filter_count += 1;
                        }
                    }
                    ReadFilterValue::Arg(arg_name) => {
                        let arg_decl = action_read
                            .arguments
                            .iter()
                            .find(|a| a.name == *arg_name)
                            .expect("arg reference validated during parsing");

                        if is_option_type(&arg_decl.ty) {
                            // Optional: only push the clause when Some
                            quote::quote! {
                                if let Some(ref val) = args.#arg_name {
                                    if filter_count > 0 { builder.push(" AND "); } else { builder.push("WHERE "); }
                                    builder.push(format!("{} {} ", #field_str, #op)).push_bind(val.clone());
                                    filter_count += 1;
                                }
                            }
                        } else {
                            // Required: always push
                            quote::quote! {
                                if filter_count > 0 { builder.push(" AND "); } else { builder.push("WHERE "); }
                                builder.push(format!("{} {} ", #field_str, #op)).push_bind(args.#arg_name.clone());
                                filter_count += 1;
                            }
                        }
                    }
                }
            }).collect();

            quote::quote! {
                impl cinderblock_sqlx::SqlReadAction for #action_name {
                    fn bind_filters(
                        builder: &mut cinderblock_sqlx::sqlx::QueryBuilder<'_, cinderblock_sqlx::sqlx::Sqlite>,
                        args: &Self::Arguments,
                    ) -> bool {
                        let mut filter_count: u32 = 0;
                        #(#filter_stmts)*
                        filter_count > 0
                    }
                }
            }
        });

    quote::quote! {
        impl cinderblock_sqlx::SqlResource for #ident {
            const TABLE_NAME: &'static str = #table_name;
            const COLUMN_NAMES: &'static [&'static str] = &[#(#column_name_literals),*];
            const INSERT_COLUMN_NAMES: &'static [&'static str] = &[#(#insert_column_name_literals),*];
            const PRIMARY_KEY_COLUMN: &'static str = #pk_column;

            fn bind_insert(
                &self,
                builder: &mut cinderblock_sqlx::sqlx::QueryBuilder<'_, cinderblock_sqlx::sqlx::Sqlite>,
            ) {
                let mut sep = builder.separated(", ");
                #(#bind_insert_calls)*
            }

            fn bind_update(
                &self,
                builder: &mut cinderblock_sqlx::sqlx::QueryBuilder<'_, cinderblock_sqlx::sqlx::Sqlite>,
            ) {
                let mut sep = builder.separated(", ");
                #(#bind_update_calls)*
            }

            fn bind_primary_key(
                pk: &<Self as cinderblock_core::Resource>::PrimaryKey,
                builder: &mut cinderblock_sqlx::sqlx::QueryBuilder<'_, cinderblock_sqlx::sqlx::Sqlite>,
            ) {
                builder.push_bind(pk.clone());
            }

            fn from_row(
                row: &cinderblock_sqlx::sqlx::sqlite::SqliteRow,
            ) -> cinderblock_core::Result<Self> {
                use cinderblock_sqlx::sqlx::Row;
                Ok(Self {
                    #(#from_row_fields)*
                })
            }
        }

        #(#read_actions)*
    }
    .into()
}

// ---------------------------------------------------------------------------
// # Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use assert2::{assert, check};

    use super::*;

    fn parse_config(tokens: proc_macro2::TokenStream) -> SqlxConfig {
        let result = syn::parse2::<SqlxConfig>(tokens);
        assert!(let Ok(config) = result);
        config
    }

    #[test]
    fn parse_table_config() {
        let config = parse_config(quote::quote! {
            table = "tickets";
        });

        check!(config.table == "tickets");
    }

    #[test]
    fn missing_table_produces_error() {
        let result = syn::parse2::<SqlxConfig>(quote::quote! {});

        assert!(let Err(err) = result);
        let msg = err.to_string();
        check!(msg.contains("requires `table"));
    }

    #[test]
    fn unknown_config_key_produces_error() {
        let result = syn::parse2::<SqlxConfig>(quote::quote! {
            table = "tickets";
            bogus = "value";
        });

        assert!(let Err(err) = result);
        let msg = err.to_string();
        check!(msg.contains("unexpected cinderblock_sqlx config key"));
        check!(msg.contains("bogus"));
    }

    #[test]
    fn table_with_schema_prefix() {
        let config = parse_config(quote::quote! {
            table = "helpdesk_tickets";
        });

        check!(config.table == "helpdesk_tickets");
    }

    // Verify the full extension input parses correctly — this uses the
    // same `ExtensionMacroInput<SqlxConfig>` that the proc macro does.
    #[test]
    fn parse_full_extension_input() {
        let tokens = quote::quote! {
            {
                name = Helpdesk.Support.Ticket;

                attributes {
                    ticket_id Uuid {
                        primary_key true;
                        writable false;
                        default || uuid::Uuid::new_v4();
                    }
                    subject String;
                    status TicketStatus;
                }

                actions {
                    create open;
                }
            }

            config = {
                table = "tickets";
            }
        };

        let result = syn::parse2::<ExtensionMacroInput<SqlxConfig>>(tokens);
        assert!(let Ok(input) = result);
        check!(input.config.table == "tickets");
        check!(input.resource.attributes.len() == 3);

        // Verify primary key detection.
        let pk = input
            .resource
            .attributes
            .iter()
            .find(|a| a.primary_key.value());
        assert!(let Some(pk_attr) = pk);
        check!(pk_attr.name == "ticket_id");
    }
}
