//! SQLite persistence extension for cinderblock resources using
//! [SQLx](https://crates.io/crates/sqlx).
//!
//! When a resource declares `cinderblock_sqlx` in its `extensions { ... }`
//! block, the [`resource!`](cinderblock_core::resource) macro generates a
//! [`SqlResource`] trait impl that provides table metadata, column bind
//! methods, and row decoding. At runtime,
//! [`SqliteDataLayer`](sqlite::SqliteDataLayer) uses these generated methods
//! to build and execute SQL queries.
//!
//! # Extension configuration
//!
//! Inside the `extensions` block of a [`resource!`](cinderblock_core::resource)
//! invocation:
//!
//! ```rust,ignore
//! extensions {
//!     cinderblock_sqlx {
//!         // Required: the SQL table name to store this resource in.
//!         table = "tickets";
//!     };
//! }
//! ```
//!
//! The only configuration is the `table` name. Column names are derived
//! automatically from attribute names using `snake_case`.
//!
//! # Database-generated columns
//!
//! Attributes marked `generated true` are omitted from INSERT and UPDATE
//! statements — their values come from the database (e.g. autoincrement
//! primary keys, server-side DEFAULT expressions). The column is still
//! read back via `RETURNING *` / SELECT so the Rust struct always has the
//! correct database-assigned value.
//!
//! ```rust,ignore
//! attributes {
//!     id i64 {
//!         primary_key true;
//!         generated true;     // Database provides the value via AUTOINCREMENT
//!         writable false;
//!     }
//!     title String;
//! }
//! ```
//!
//! # Type mapping
//!
//! This extension deliberately does **not** define its own type-mapping trait.
//! Instead, it relies on SQLx's existing [`sqlx::Type`], [`sqlx::Encode`], and
//! [`sqlx::Decode`] implementations. The generated [`SqlResource`] methods use
//! `QueryBuilder::push_bind()` (which requires `Encode + Type`) and
//! `Row::try_get()` (which requires `Decode + Type`).
//!
//! For custom types like enums, implement SQLx's traits directly — for
//! example via `#[derive(sqlx::Type)]` or a serde-based approach.
//!
//! # Read filters
//!
//! Read actions with `filter` clauses in the `resource!` DSL generate a
//! [`SqlReadAction`] impl. The generated `bind_filters` method dynamically
//! builds `WHERE` clauses:
//!
//! - **Literal filters** (`filter { status == TicketStatus::Open }`) always
//!   emit a `WHERE column = ?` clause.
//! - **Argument-bound filters** (`filter { status == arg(status) }`) bind the
//!   runtime argument value. When the argument type is `Option<T>` and the
//!   value is `None`, the clause is omitted entirely.
//!
//! # Setup
//!
//! Register a [`SqliteDataLayer`](sqlite::SqliteDataLayer) on the
//! [`Context`](cinderblock_core::Context) so resources can use it:
//!
//! ```rust,ignore
//! use cinderblock_core::Context;
//! use cinderblock_sqlx::sqlite::SqliteDataLayer;
//!
//! let pool = sqlx::SqlitePool::connect("sqlite::memory:").await?;
//! let mut ctx = Context::new();
//! ctx.register_data_layer(SqliteDataLayer::new(pool));
//! ```
//!
//! Then set the resource's data layer in the `resource!` DSL:
//!
//! ```rust,ignore
//! resource! {
//!     name = Helpdesk.Support.Ticket;
//!     data_layer = cinderblock_sqlx::sqlite::SqliteDataLayer;
//!
//!     attributes {
//!         ticket_id Uuid {
//!             primary_key true;
//!             writable false;
//!             default || Uuid::new_v4();
//!         }
//!         subject String;
//!         status String;
//!     }
//!
//!     actions {
//!         read all;
//!         create open;
//!         update edit;
//!         destroy remove;
//!     }
//!
//!     extensions {
//!         cinderblock_sqlx {
//!             table = "tickets";
//!         };
//!     }
//! }
//! ```

use cinderblock_core::ReadAction;
pub use cinderblock_sqlx_macros::__resource_extension;
pub use sqlx;

pub mod sqlite;

// ---------------------------------------------------------------------------
// # SqlResource Trait
// ---------------------------------------------------------------------------

/// Schema and row-conversion interface for resources stored in SQL.
///
/// This trait is generated by the `cinderblock_sqlx` extension macro. It provides
/// the table name, column metadata, and methods to bind a resource into
/// an INSERT/UPDATE query and to decode one from a row.
///
/// The generated methods lean on sqlx's native `Encode`/`Decode`/`Type`
/// impls rather than a framework-specific trait, so any type that sqlx
/// already knows how to handle (String, integers, bool, Uuid with the
/// `uuid` feature, etc.) just works.
pub trait SqlResource: cinderblock_core::Resource {
    const TABLE_NAME: &'static str;

    /// All column names on the table, in declaration order. Used for
    /// SELECT and from_row decoding.
    const COLUMN_NAMES: &'static [&'static str];

    /// Column names included in INSERT statements — excludes columns
    /// marked `generated true`, whose values are provided by the database
    /// (e.g. autoincrement primary keys, server-side defaults).
    const INSERT_COLUMN_NAMES: &'static [&'static str];

    const PRIMARY_KEY_COLUMN: &'static str;

    /// Push bind values for non-generated columns into the query builder,
    /// separated by commas (in the same order as `INSERT_COLUMN_NAMES`).
    ///
    /// Columns marked `generated true` are omitted — those values come
    /// from the database itself.
    ///
    /// The caller is responsible for emitting the `INSERT INTO ... VALUES (`
    /// prefix before calling this, and the closing `)` afterwards.
    fn bind_insert(&self, builder: &mut sqlx::QueryBuilder<'_, sqlx::Sqlite>);

    /// Push bind values for non-primary-key, non-generated columns into the
    /// query builder, each as `column_name = ?` separated by commas.
    ///
    /// The caller emits `UPDATE table SET ` before calling this, and
    /// ` WHERE pk = ?` afterwards.
    fn bind_update(&self, builder: &mut sqlx::QueryBuilder<'_, sqlx::Sqlite>);

    /// Push the primary key value as a bind parameter.
    ///
    /// This is a generated method so the concrete PK type's `Encode` impl
    /// is used directly, without needing sqlx bounds on the `SqlResource`
    /// trait definition itself.
    fn bind_primary_key(
        pk: &<Self as cinderblock_core::Resource>::PrimaryKey,
        builder: &mut sqlx::QueryBuilder<'_, sqlx::Sqlite>,
    );

    /// Decode all columns from a row and reconstruct the resource.
    fn from_row(row: &sqlx::sqlite::SqliteRow) -> cinderblock_core::Result<Self>;
}

pub trait SqlReadAction: ReadAction {
    /// Conditionally push filter clauses (including the WHERE keyword) into
    /// the query builder. Returns `true` if any WHERE conditions were added.
    ///
    /// This method handles the WHERE keyword internally so that optional
    /// arguments (which may or may not produce a clause) work correctly
    /// without the caller needing to predict the filter count.
    fn bind_filters(builder: &mut sqlx::QueryBuilder<'_, sqlx::Sqlite>, args: &Self::Arguments)
        -> bool;
}
