// # Ash SQLx Extension
//
// Data layer extension that stores resources in SQL databases via `sqlx`.
// Currently supports SQLite with one column per resource attribute.
//
// The extension follows the same pattern as `ash-json-api`:
//   1. User declares `ash_sqlx { table = "tickets"; }` in their resource's
//      `extensions` block
//   2. `resource!` forwards the raw tokens to `ash_sqlx::__resource_extension!`
//   3. The proc macro generates a `SqlResource` impl for the resource
//   4. At runtime, `SqliteDataLayer` uses `SqlResource` to build and
//      execute SQL queries
//
// # Type mapping philosophy
//
// We deliberately do NOT define our own type-mapping trait. Instead, we
// rely on sqlx's existing `Type`, `Encode`, and `Decode` implementations.
// The generated `SqlResource` methods use `QueryBuilder::push_bind()` (which
// requires `Encode + Type`) and `Row::try_get()` (which requires `Decode +
// Type`). For custom types like enums, the user implements sqlx's traits
// directly — or uses `#[sqlx(type_name = "...")]` / serde-based approaches.

pub use ash_sqlx_macros::__resource_extension;
pub use sqlx;

pub mod sqlite;

// ---------------------------------------------------------------------------
// # SqlResource Trait
// ---------------------------------------------------------------------------

/// Schema and row-conversion interface for resources stored in SQL.
///
/// This trait is generated by the `ash_sqlx` extension macro. It provides
/// the table name, column metadata, and methods to bind a resource into
/// an INSERT/UPDATE query and to decode one from a row.
///
/// The generated methods lean on sqlx's native `Encode`/`Decode`/`Type`
/// impls rather than a framework-specific trait, so any type that sqlx
/// already knows how to handle (String, integers, bool, Uuid with the
/// `uuid` feature, etc.) just works.
pub trait SqlResource: ash_core::Resource {
    const TABLE_NAME: &'static str;
    const COLUMN_NAMES: &'static [&'static str];
    const PRIMARY_KEY_COLUMN: &'static str;

    /// Push bind values for all columns into the query builder, separated
    /// by commas (in the same order as `COLUMN_NAMES`).
    ///
    /// The caller is responsible for emitting the `INSERT INTO ... VALUES (`
    /// prefix before calling this, and the closing `)` afterwards.
    fn bind_insert(&self, builder: &mut sqlx::QueryBuilder<'_, sqlx::Sqlite>);

    /// Push bind values for non-primary-key columns into the query builder,
    /// each as `column_name = ?` separated by commas.
    ///
    /// The caller emits `UPDATE table SET ` before calling this, and
    /// ` WHERE pk = ?` afterwards.
    fn bind_update(&self, builder: &mut sqlx::QueryBuilder<'_, sqlx::Sqlite>);

    /// Push the primary key value as a bind parameter.
    ///
    /// This is a generated method so the concrete PK type's `Encode` impl
    /// is used directly, without needing sqlx bounds on the `SqlResource`
    /// trait definition itself.
    fn bind_primary_key(
        pk: &<Self as ash_core::Resource>::PrimaryKey,
        builder: &mut sqlx::QueryBuilder<'_, sqlx::Sqlite>,
    );

    /// Decode all columns from a row and reconstruct the resource.
    fn from_row(row: &sqlx::sqlite::SqliteRow) -> ash_core::Result<Self>;
}
